// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAWScrum.Data.Context;

#nullable disable

namespace PAWScrum.Data.Migrations
{
    [DbContext(typeof(PAWScrumDbContext))]
    partial class PAWScrumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAWScrum.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__Activity__5E54864809C064DC");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("PAWScrum.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SprintItemId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Comments__C3B4DFCAEA75DC6D");

                    b.HasIndex("SprintItemId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PAWScrum.Models.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursCompleted")
                        .HasColumnType("int");

                    b.Property<int>("HoursEstimated")
                        .HasColumnType("int");

                    b.Property<int>("ProductBacklogItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ProductBacklogItemId");

                    b.ToTable("WorkTasks");
                });

            modelBuilder.Entity("PAWScrum.Models.ProductBacklogItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemId")
                        .HasName("PK__ProductB__727E838B0C383396");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProductBacklogItems");
                });

            modelBuilder.Entity("PAWScrum.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Private");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABEF0AFF11888");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PAWScrum.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("PK__ProjectM__A76232346906DF47");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("PAWScrum.Models.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SprintId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SprintId")
                        .HasName("PK__Sprints__29F16AC0B58C4F9D");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("PAWScrum.Models.SprintBacklogItem", b =>
                {
                    b.Property<int>("SprintItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SprintItemId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompletedHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("EstimationHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("ProductBacklogItemId")
                        .HasColumnType("int");

                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SprintItemId")
                        .HasName("PK__SprintBa__B07E5F760CDB7026");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ProductBacklogItemId");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintBacklogItems");
                });

            modelBuilder.Entity("PAWScrum.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C4A27407A");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E48AE1EE81")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534A01BED78")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PAWScrum.Models.UserTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompletedHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimationHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SprintItemId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949B15F1BC7FE");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("SprintItemId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PAWScrum.Models.ActivityLog", b =>
                {
                    b.HasOne("PAWScrum.Models.Project", "Project")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__ActivityL__Proje__5BE2A6F2");

                    b.HasOne("PAWScrum.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ActivityL__UserI__5AEE82B9");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PAWScrum.Models.Comment", b =>
                {
                    b.HasOne("PAWScrum.Models.SprintBacklogItem", "SprintItem")
                        .WithMany("Comments")
                        .HasForeignKey("SprintItemId")
                        .HasConstraintName("FK__Comments__Sprint__5629CD9C");

                    b.HasOne("PAWScrum.Models.UserTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK__Comments__TaskId__571DF1D5");

                    b.HasOne("PAWScrum.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__UserId__5535A963");

                    b.Navigation("SprintItem");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PAWScrum.Models.Entities.WorkTask", b =>
                {
                    b.HasOne("PAWScrum.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("PAWScrum.Models.ProductBacklogItem", "ProductBacklogItem")
                        .WithMany()
                        .HasForeignKey("ProductBacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("ProductBacklogItem");
                });

            modelBuilder.Entity("PAWScrum.Models.ProductBacklogItem", b =>
                {
                    b.HasOne("PAWScrum.Models.Project", "Project")
                        .WithMany("ProductBacklogItems")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductBa__Proje__48CFD27E");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PAWScrum.Models.Project", b =>
                {
                    b.HasOne("PAWScrum.Models.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Projects__OwnerI__3E52440B");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PAWScrum.Models.ProjectMember", b =>
                {
                    b.HasOne("PAWScrum.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__ProjectMe__Proje__412EB0B6");

                    b.HasOne("PAWScrum.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ProjectMe__UserI__4222D4EF");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PAWScrum.Models.Sprint", b =>
                {
                    b.HasOne("PAWScrum.Models.Project", "Project")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Sprints__Project__44FF419A");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PAWScrum.Models.SprintBacklogItem", b =>
                {
                    b.HasOne("PAWScrum.Models.User", "AssignedToNavigation")
                        .WithMany("SprintBacklogItems")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__SprintBac__Assig__4D94879B");

                    b.HasOne("PAWScrum.Models.ProductBacklogItem", "ProductBacklogItem")
                        .WithMany("SprintBacklogItems")
                        .HasForeignKey("ProductBacklogItemId")
                        .IsRequired()
                        .HasConstraintName("FK__SprintBac__Produ__4CA06362");

                    b.HasOne("PAWScrum.Models.Sprint", "Sprint")
                        .WithMany("SprintBacklogItems")
                        .HasForeignKey("SprintId")
                        .IsRequired()
                        .HasConstraintName("FK__SprintBac__Sprin__4BAC3F29");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("ProductBacklogItem");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("PAWScrum.Models.UserTask", b =>
                {
                    b.HasOne("PAWScrum.Models.User", "AssignedToNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Tasks__AssignedT__5165187F");

                    b.HasOne("PAWScrum.Models.SprintBacklogItem", "SprintItem")
                        .WithMany("Tasks")
                        .HasForeignKey("SprintItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__SprintIte__5070F446");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("SprintItem");
                });

            modelBuilder.Entity("PAWScrum.Models.ProductBacklogItem", b =>
                {
                    b.Navigation("SprintBacklogItems");
                });

            modelBuilder.Entity("PAWScrum.Models.Project", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ProductBacklogItems");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("PAWScrum.Models.Sprint", b =>
                {
                    b.Navigation("SprintBacklogItems");
                });

            modelBuilder.Entity("PAWScrum.Models.SprintBacklogItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PAWScrum.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Comments");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Projects");

                    b.Navigation("SprintBacklogItems");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PAWScrum.Models.UserTask", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
